-- Durable idempotency for WG Almeida site contact intake.
-- Canonical model: pessoas + contact_interactions. Does NOT recreate legacy contacts table.

BEGIN;

CREATE TABLE IF NOT EXISTS public.site_contact_idempotency (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  fingerprint text NOT NULL UNIQUE,
  pessoa_id uuid NULL REFERENCES public.pessoas(id) ON DELETE SET NULL,
  interaction_id uuid NULL REFERENCES public.contact_interactions(id) ON DELETE SET NULL,
  request_id uuid NULL,
  outcome text NOT NULL DEFAULT 'processing',
  promotion_outcome text NOT NULL DEFAULT 'promotion_skipped',
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz NOT NULL,
  CONSTRAINT site_contact_idempotency_outcome_check
    CHECK (outcome IN ('processing','saved')),
  CONSTRAINT site_contact_idempotency_promotion_check
    CHECK (promotion_outcome IN ('promotion_skipped','promotion_completed'))
);

COMMENT ON TABLE public.site_contact_idempotency IS
  'Durable, non-PII idempotency keys for WG Almeida site contact submissions.';
COMMENT ON COLUMN public.site_contact_idempotency.fingerprint IS
  'SHA-256 fingerprint generated by the API from normalized contact payload. Never store the raw PII used to derive it.';

CREATE INDEX IF NOT EXISTS idx_site_contact_idempotency_expires_at
  ON public.site_contact_idempotency(expires_at);

ALTER TABLE public.site_contact_idempotency ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.site_contact_idempotency FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.site_contact_idempotency TO service_role;

CREATE OR REPLACE FUNCTION public.ingest_site_contact_idempotent(
  p_fingerprint text,
  p_request_id uuid,
  p_name text,
  p_email text,
  p_phone text DEFAULT NULL,
  p_subject text DEFAULT NULL,
  p_message text DEFAULT NULL,
  p_utm_source text DEFAULT NULL,
  p_utm_medium text DEFAULT NULL,
  p_utm_campaign text DEFAULT NULL,
  p_origem text DEFAULT 'site',
  p_context text DEFAULT NULL,
  p_promote boolean DEFAULT false,
  p_ttl_seconds integer DEFAULT 120
)
RETURNS TABLE(
  outcome text,
  pessoa_id uuid,
  interaction_id uuid,
  promotion_outcome text
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_key public.site_contact_idempotency%ROWTYPE;
  v_pessoa_id uuid;
  v_interaction_id uuid;
  v_email text;
  v_promotion text := 'promotion_skipped';
  v_existing boolean := false;
BEGIN
  IF p_fingerprint IS NULL OR length(trim(p_fingerprint)) < 32 THEN
    RAISE EXCEPTION 'invalid_fingerprint';
  END IF;

  v_email := lower(trim(coalesce(p_email, '')));
  IF v_email = '' OR position('@' in v_email) <= 1 THEN
    RAISE EXCEPTION 'invalid_email';
  END IF;

  IF nullif(trim(coalesce(p_name, '')), '') IS NULL THEN
    RAISE EXCEPTION 'invalid_name';
  END IF;

  IF nullif(trim(coalesce(p_message, '')), '') IS NULL THEN
    RAISE EXCEPTION 'invalid_message';
  END IF;

  -- Allow the same normalized submission again only after its TTL expires.
  DELETE FROM public.site_contact_idempotency
  WHERE fingerprint = p_fingerprint
    AND expires_at <= now();

  INSERT INTO public.site_contact_idempotency (
    fingerprint, request_id, outcome, promotion_outcome, metadata, expires_at
  ) VALUES (
    p_fingerprint,
    p_request_id,
    'processing',
    'promotion_skipped',
    jsonb_build_object(
      'context', nullif(trim(coalesce(p_context, '')), ''),
      'origem', nullif(trim(coalesce(p_origem, '')), '')
    ),
    now() + make_interval(secs => greatest(30, least(coalesce(p_ttl_seconds, 120), 3600)))
  )
  ON CONFLICT (fingerprint) DO NOTHING
  RETURNING * INTO v_key;

  IF v_key.id IS NULL THEN
    SELECT * INTO v_key
    FROM public.site_contact_idempotency
    WHERE fingerprint = p_fingerprint;

    RETURN QUERY
    SELECT
      'duplicate'::text,
      v_key.pessoa_id,
      v_key.interaction_id,
      v_key.promotion_outcome;
    RETURN;
  END IF;

  -- Serialize same-email creation without imposing a global unique constraint on legacy data.
  PERFORM pg_advisory_xact_lock(hashtextextended(v_email, 0));

  SELECT p.id INTO v_pessoa_id
  FROM public.pessoas p
  WHERE p.ativo = true
    AND lower(trim(coalesce(p.email, ''))) = v_email
  ORDER BY p.created_at ASC NULLS LAST, p.id
  LIMIT 1
  FOR UPDATE;

  IF v_pessoa_id IS NULL THEN
    INSERT INTO public.pessoas (
      nome,
      email,
      telefone,
      tipo,
      ativo,
      cadastro_automatico,
      origem_cadastro,
      revisao_pendente,
      contact_stage,
      lead_source,
      lead_source_ref
    ) VALUES (
      trim(p_name),
      v_email,
      nullif(trim(coalesce(p_phone, '')), ''),
      'CLIENTE',
      true,
      true,
      coalesce(nullif(trim(coalesce(p_origem, '')), ''), 'site'),
      true,
      'contato',
      'formulario',
      nullif(trim(coalesce(p_context, '')), '')
    )
    RETURNING id INTO v_pessoa_id;
  ELSE
    UPDATE public.pessoas
    SET
      telefone = CASE
        WHEN nullif(trim(coalesce(telefone, '')), '') IS NULL
          THEN nullif(trim(coalesce(p_phone, '')), '')
        ELSE telefone
      END,
      updated_at = now()
    WHERE id = v_pessoa_id;
  END IF;

  INSERT INTO public.contact_interactions (
    pessoa_id,
    source,
    source_ref,
    channel,
    direction,
    summary,
    sanitized_payload,
    intent,
    detected_by,
    requires_human_review
  ) VALUES (
    v_pessoa_id,
    'site_wgalmeida',
    nullif(trim(coalesce(p_context, '')), ''),
    'formulario_site',
    'inbound',
    left(nullif(trim(coalesce(p_subject, '')), ''), 500),
    jsonb_strip_nulls(jsonb_build_object(
      'message', left(trim(p_message), 1800),
      'utm_source', nullif(trim(coalesce(p_utm_source, '')), ''),
      'utm_medium', nullif(trim(coalesce(p_utm_medium, '')), ''),
      'utm_campaign', nullif(trim(coalesce(p_utm_campaign, '')), ''),
      'context', nullif(trim(coalesce(p_context, '')), ''),
      'origem', nullif(trim(coalesce(p_origem, '')), '')
    )),
    CASE WHEN p_context = 'moodboard-studio-v2' THEN 'validacao_moodboard' ELSE 'contato_site' END,
    'site_api',
    true
  )
  RETURNING id INTO v_interaction_id;

  IF p_promote THEN
    PERFORM *
    FROM public.fn_promover_contato_para_lead(
      v_pessoa_id,
      'formulario',
      'Solicitacao explicita recebida pelo site WG Almeida',
      v_interaction_id,
      coalesce(nullif(trim(coalesce(p_subject, '')), ''), 'Solicitacao pelo site'),
      NULL,
      NULL,
      jsonb_build_object('context', nullif(trim(coalesce(p_context, '')), ''))
    );
    v_promotion := 'promotion_completed';
  END IF;

  UPDATE public.site_contact_idempotency
  SET
    pessoa_id = v_pessoa_id,
    interaction_id = v_interaction_id,
    outcome = 'saved',
    promotion_outcome = v_promotion
  WHERE id = v_key.id;

  RETURN QUERY
  SELECT 'saved'::text, v_pessoa_id, v_interaction_id, v_promotion;
END;
$$;

COMMENT ON FUNCTION public.ingest_site_contact_idempotent IS
  'Atomically ingests WG Almeida site contacts into pessoas/contact_interactions with durable cross-instance idempotency.';

REVOKE ALL ON FUNCTION public.ingest_site_contact_idempotent(
  text, uuid, text, text, text, text, text, text, text, text, text, text, boolean, integer
) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.ingest_site_contact_idempotent(
  text, uuid, text, text, text, text, text, text, text, text, text, text, boolean, integer
) TO service_role;

-- Migration self-test. The nested block deliberately rolls back its test rows.
DO $$
DECLARE
  v_first record;
  v_second record;
  v_test_key text := '9f4d34d6e2f8d8d0f1ab8ad091c4a8f63b6e5dbe7d3f8f9a22d4c8e9f0a1b2c3';
BEGIN
  BEGIN
    SELECT * INTO v_first
    FROM public.ingest_site_contact_idempotent(
      v_test_key,
      gen_random_uuid(),
      'WG Migration Selftest',
      'wg-migration-selftest@example.invalid',
      NULL,
      'Migration self-test',
      'Temporary transactional self-test; must roll back.',
      NULL, NULL, NULL,
      'migration-selftest',
      'migration-selftest',
      false,
      120
    );

    SELECT * INTO v_second
    FROM public.ingest_site_contact_idempotent(
      v_test_key,
      gen_random_uuid(),
      'WG Migration Selftest',
      'wg-migration-selftest@example.invalid',
      NULL,
      'Migration self-test',
      'Temporary transactional self-test; must roll back.',
      NULL, NULL, NULL,
      'migration-selftest',
      'migration-selftest',
      false,
      120
    );

    IF v_first.outcome <> 'saved' OR v_second.outcome <> 'duplicate' THEN
      RAISE EXCEPTION 'idempotency_selftest_failed: first=%, second=%', v_first.outcome, v_second.outcome;
    END IF;

    RAISE EXCEPTION USING ERRCODE = 'P0001', MESSAGE = 'rollback_idempotency_selftest';
  EXCEPTION
    WHEN SQLSTATE 'P0001' THEN
      IF SQLERRM <> 'rollback_idempotency_selftest' THEN
        RAISE;
      END IF;
  END;
END;
$$;

COMMIT;
